### ISSUE TITLE
IINA Support

### ISSUE THREAD

**Issue by shawnbutts** [dehesselle/chatty#2] opened 2018-01-07 18:21 UTC
Can support for IINA (https://lhc70000.github.io/iina/) be added.

I find it performs better than VLC with twitch streams.

**Comment by dehesselle** [comment] 2018-01-07 22:42
Yes, this can be done.

However, I did some research and it looks like the current version of IINA, v0.0.14.1, is not quite there yet to be used from the command line. CLI support is being worked on and a first implementation has already been merged (see https://github.com/lhc70000/iina/pull/1181), but there hasn't been a release yet to include these changes.

If that happens, come back here and ping me so I can pick this up again.

**Comment by shawnbutts** [comment] 2018-01-13 13:50
https://github.com/lhc70000/iina/releases v0.0.15 now has a CLI tool

**Comment by dehesselle** [comment] 2018-01-13 14:51
Nice, that was quick! I've played around a bit and I'm confident I'll have something ready to test within the next week.

**Comment by dehesselle** [comment] 2018-01-17 23:55
I've made some progress today. I've reworked the scripts, only a few more personal tests and then I'll make a pre-release this week.

**Comment by dehesselle** [comment] 2018-01-18 20:46
I just released Chatty 0.9 build 19, a pre-release to test support for IINA. In fact, if IINA is found on your system (`/ Applications` and `~/Applications` is checked), it takes precedence over VLC.

There is a minor inconvenience, please read the upgrade instructions as mentioned on the release page. I'll probably provide a one-liner that people can paste into their terminal that takes care of the necessary configuration changes in the future. Also, the documentation is not up to par yet.

All in all, I'm happy with IINA although it does not always feel as robust as Streamlink/VLC. Sometimes it takes its dear time with buffering (for no apparent reason as far as I can tell), something I don't experience with Streamlink/VLC. I do have a beefy internet connection, that's not the issue (also confirmed by cross-testing with Streamlink/VLC). It might be fixable with adjusting some caching parameters (there are a lot!) and/or me not having enough experience with mpv and how to correctly use it for streaming, but that's something to figure out by using and testing this for a while.

This issue will remain open until this either goes into production (I want that) or gets discarded (unlikely, only mentioning it for completeness' sake).

**Comment by shawnbutts** [comment] 2018-01-18 23:30
Only had 2 issues with it.  

1) had to uncheck "Use Authorization.." under the base command setting.  
2) selection "Source" from the context menu didn't work.  selecting any other option worked.

Both easily worked around.  :) Thanks for working on this so quickly.

**Comment by dehesselle** [comment] 2018-01-19 00:44
Thank you for your feedback.

1. `Use Authorization...` is Livestreamer/Streamlink specific. I've never used it myself, hence it did not occur to me to test that. I'll check if this is something I can catch and just ignore when IINA is used so that one does not have to enable/disable this depending on the player that's being used.
2. I've already had a little bit of back and forth with this one, too. It would help me a lot if you can tell me exactly what you're doing. As a reference, I do right click in the chat window, select `Livestreamer`, select `Select` and a dialog opens presenting me all quality options. The last one (source) has as suffix `__source_`. It is supposed to work like the other options - is that what doesn't work in your case? Does it always break or only on specific streams (examples?)?

**Comment by shawnbutts** [comment] 2018-01-19 09:25
I'm doing the same thing with Select.  It seems to be break constantly when selecting source.  But, I only check 2 streams.  I'll check a few more this evening.

**Comment by dehesselle** [comment] 2018-01-20 15:43
A few examples would be helpful for me to reproduce the issue.

What exactly happens? Does IINA open, but stays black with a message "buffering"? Or do you get an "unable to open stream" error?

**Comment by shawnbutts** [comment] 2018-01-28 18:56
Sorry it took me so long to get back to this.  I get an "unable to open stream" message.

I think I've tracked it down to how it finds the correct "source" setting.  When I get the error, the format is set to "--mpv-ytdl-format=source".  But, if i select "best" it uses the correct option like "--mpv-ytdl-format=522p60__source_"

**Comment by dehesselle** [comment] 2018-01-28 19:49
Just to be absolutely clear (and that I'm not digging in the wrong place): what did you do to set it to "source"? Did you customize the Livestreamer context menu and put "source" there next to "worst", "best" and "select"?

**Comment by shawnbutts** [comment] 2018-01-28 19:59
I thought it was there automatically.  But, I guess I did add source manually.  I'll remove it and just use best.  Sorry for waisting your time debugging this.

**Comment by dehesselle** [comment] 2018-01-28 20:17
No worries. Since "source" does not work with Streamlink either, it's best to remove it like you did.

**Comment by dehesselle** [comment] 2018-04-15 13:13
<img width="575" alt="iina_ytdl_buffering" src="https://user-images.githubusercontent.com/11375494/38778749-7090c6d6-40be-11e8-93b1-98bacbcb13dd.png">
A lot of the time I'm getting buffering issues using IINA (that utilitzes a bundled youtube-dl) whereas Streamlink+VLC never fails. IINA support will stay and be part of the next release, but will not be the default or preferred choice. There will be a mechanism like the user having to perform `touch ~/.chattyuseiina` to enable IINA becoming the preferred choice.

**Comment by dehesselle** [comment] 2019-05-16 23:02
...time has passed...
This shall be brought to a close with the next release.

**Comment by dehesselle** [comment] 2019-06-08 23:30
The new release uses IINA as preferred choice if present.

**Closed as completed by dehesselle** 2019-06-08 23:30 UTC
Labels: enhancement
